### ISSUE TITLE
fs.readFileSync() in client code

### ISSUE THREAD

**Issue by regular** [ssbc/patchbay#116]
hi, I tried to build index.html to serve it to a browser using

```
browserify main.js | indexhtmlify --title patchbay > build/index.html
```
(as mentioned in the Readme).

The resulting file however contains  [this call to fs.readFileSync](https://github.com/ssbc/patchbay/blame/53d03c145268665aa93e60777b4153a8a0c4dca5/app/styles/css/font-awesome.js#L8) and the browser actually hits that code.

I might be totally wrong about how this is meant to work :/

**Comment by dominictarr** [comment]
hmm, brfs is ment to be able to handle that but I think @ahdinosaur broke it in this commit. https://github.com/ssbc/patchbay/commit/53d03c145268665aa93e60777b4153a8a0c4dca5

**Comment by ahdinosaur** [comment]
hey @regular, if you want to run `patchbay` in the browser, i recommend [`patchlite`](https://github.com/ssbc/patchlite) which `patchbay` + a few modules to make everything work in the browser.

@dominictarr `patchlite` hasn't worked with the latest `patchbay` since those fonts were added, we've kept `patchlite` at the latest working commit: https://github.com/ssbc/patchlite/pull/2. i'm hoping to make it work with the latest `patchbay` again and that change is one step closer.

**Comment by dominictarr** [comment]
@ahdinosaur what does styleResolve do?

**Comment by ahdinosaur** [comment]
@dominictarr https://github.com/stackcss/style-resolve#usage

did a pass at making this work: https://github.com/ssbc/patchbay/pull/117

**Comment by mixmix** [comment]
Cool, can look at art hack tmrw.

**Comment by christianbundy** [comment]
I see that #117 was merged, does that mean that this is ready to close?
