### ISSUE TITLE
I seem to keep getting this issue with installation.

### ISSUE THREAD

**Issue by LWFlouisa** [ssbc/patchbay#245]
Error: The module '/home/sarah/patchbay/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (/home/sarah/patchbay/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/sarah/patchbay/node_modules/leveldown/leveldown.js:4:46)

But I'm basically having to install through terminal, since Scuttlebutt keeps interrupting its download. When the entire point of it is to be able to work offline, and sync up once you're online.

**Comment by cryptix** [comment]
Sorry you had to go through with this. Sadly the offline-first aspects only kick in after you have a working installation...

Regarding the error: what distribution are you using and how did you install nodejs/npm? We sometimes recommend [nvm](https://github.com/creationix/nvm) to line up electron and nodes ABI versions.

Also: do you have a specific reason to install from source? have tried using the appImage from the binary releases?  https://github.com/ssbc/patchbay/releases/tag/v7.14.0 (you might need to `chmod u+x patchbay.appImage` before you can start it)

**Comment by christianbundy** [comment]
If you're building from source, your problem *could* be that you need to (re)run `npm run rebuild`. We need to make sure that our Node modules are built to target the version of Node that's packaged with Electron, not necessarily the version you're running locally on your computer.

Also, since it's bitten me before, note that `npm run rebuild` does the exact opposite of `npm rebuild`. The one with `run` is a script from Patchbay that rebuilds for Electron, whereas the regular `npm rebuild` is an NPM command that rebuilds for your local version of Node. Hope this helps!
