### ISSUE TITLE
clicking on heart icon in /posts does not activate it

### ISSUE THREAD

**Issue by albill** [ssbc/patchbay#315]
If you click on the heart icon to "dig" a post in /posts when looking at the entire list, it does nothing. From what I can see, you must open an individual post in order for the activation to work on that page (and even then hit detection is pretty iffy).

**Comment by mixmix** [comment]
that's not a link - it's only a view of how many like there are. I've deliberatly not enabled top level liking because I'm of the opinion that you should have to open the thread to be able to engage.

this is useful feedback though.

hit detection happen in threads it's just it's slow to publish and re-render that element if you're also replication. This is a frustrating and known issue which will be resolved with some upcoming database changes :)

**Comment by mixmix** [comment]
closing this now
