### ISSUE TITLE
run patchbay on a headless server

### ISSUE THREAD

**Issue by khimaros** [ssbc/patchbay#329]
I have a server which I use to run my `sbot server`. I'd love to host patchwork as a web service so that I could browse from my laptop/phone.

Is such a thing already possible?

**Comment by cryptix** [comment]
no I think it’s to entangled into electron right now.

If you really want a web frontend today you could try patchfoo and put it behind basic auth but I think you need to install ssb-npm  or git-ssb first.

**Comment by mixmix** [comment]
It could be possible to do this. It is quite entangled with eletron but not inseperable. The main question / challenge is "how would you authenticate yourself" from the server?

**Comment by christianbundy** [comment]
@mixmix 

One way to do it would be to copy the way I did [authentication in ssb-compose](https://github.com/fraction/ssb-compose/blob/192bb138a4a8e9b9c4c05b2a4a428292727572c0/src/server.js#L41-L46). When the server starts it generates a random token and it only responds to requests like:

```
https://localhost/?token=<token>
```

Each time the server starts it generates a new token so that there aren't any long-term secrets exposed in your browser history, and _ideally_ the browser could cache the secret in localStorage or something (although you'd probably want to serve on `<random>.localhost` or something so other localhost apps can't steal your keys). Lots of interesting ideas in this space, I'm super interested in building a localhost launcher.

**Comment by khimaros** [comment]
For my personal use case, it would be sitting behind a reverse proxy which handles authentication/authorization.
