### ISSUE TITLE
Styling is a bit weird, text hard to read

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchbay#360]
Running latest master. I don't think it's looked like this before but I'm getting some deja vu. No custom styles.

![image](https://user-images.githubusercontent.com/1427063/68960870-568f1b80-07d1-11ea-8a22-1d782cc11094.png)

**Comment by christianbundy** [comment]
It's the emoji font! I've had this since the noto color emoji font was added. Happy to chat more about this if you'd like, we had to fix it in Patchwork.

**Comment by Powersource** [comment]
Sure, would be nice to fix. How was it fixed in patchwork?

**Comment by christianbundy** [comment]
Instead of setting a `font-family: NotoColorEmoji` on *all text* we do:

```css
.emoji {
  font-family: NotoColorEmoji;
}
```

Then you just pass an `emoji` property to ssb-markdown with a function like:

https://github.com/ssbc/patchwork/blob/c76136fb1628ec7fd4bb10b181d70ced01bb120c/lib/depject/message/html/markdown.js#L49-L57

(You can ignore the `emojiMentions[emoji]` condition, that's for Patchwork's "custom emoji" functionality that I've never actually seen working.)

**Comment by Powersource** [comment]
Remember that we need to update patchcore in patchbay before it works

**Comment by Powersource** [comment]
Can't get patchbay to build atm but I think this issue still applies since patchcore hasn't had a new release.
