### ISSUE TITLE
Is project being maintained?

### ISSUE THREAD

**Issue by georgeowell** [ssbc/patchbay#373]
I spoke to @mixmix on SSB and they said they aren't maintaining Patchbay any more. I saw @arj03 and others make a few small commits. 

Shall we put a note in the README about this for clarity?

This also links to #371 in the sense that most users are on whatever the last binary release was.

**Comment by arj03** [comment]
Putting a note in README would be a good idea. Happy to merge such a PR

**Comment by mixmix** [comment]
Hmm, not sure how best to say it.
I'm still using patchbay and I'm currently working to update it to the
latest ssb-db to support private groups.

I'm not that intetested in developing new features. I'm mainly intetested
in fixing bugs if they effect me or a direct friend. So some maintenance
but not all maintenance.

I'm intetested in building a newer client with better patterns

**Comment by georgeowell** [comment]
I think that stills counts as maintaining it somewhat but perhaps we are looking for maintainers? 

I take it you don't want to test and merge pull requests?

**Comment by mixmix** [comment]
Correct I don't want to test + merge. I think I'd also feel weird about others testing / merging who I don't know?
Mainly because if I'm going to fix things I don't want massive unknown change in there.

Perhaps it's best for me to either fork off, or ask others to?
Honestly I don't think we should maintain, I think we should build fresh... but I'm biased
