### ISSUE TITLE
Reply to reply disappears

### ISSUE THREAD

**Issue by clehner** [ssbc/patchbay#38]
If you open a tab for a message that is a reply, and you compose and publish a reply there, your message disappears from the compose box but does not appear in the tab. This makes it look like patchbay "ate" the message and led to me posting a duplicate reply today. I think the rest of a thread should render under a reply, or the composer shouldn't be there.

**Comment by dominictarr** [comment]
Hmm, another option, would be to show the entire thread, but with the linked to message emphasized,
and scroll the UI to that element when it loads (which is analogous to how twitter does it)

**Comment by evbogue** [comment]
This still happens.

**Comment by dominictarr** [comment]
can you link me to a message that has this problem?

**Comment by evbogue** [comment]
This just happened, 21 seconds ago. 

The issue is you have a reply open. You attempt to reply to the reply. Bay appears to publish the reply to the reply, and you either think that it published or you think that it didn't publish. 

In this case it actually _didn't_ publish. in this case @gwenbell ended up copy and pasting, and reloading Bay, then publishing.

I'm not sure what else I can do to speculate about why this may be happening. The only thing I know is it has to do with tabs being open for long periods of time. 

In other cases I've hit publish, and Bay _does_ publish, but it doesn't show up and then I think it ate it. Then I reload Bay and it's there.

Regardless, I find myself systematically copying posts before I hit send on them. Definitely long ones.

**Comment by christianbundy** [comment]
Is anyone still getting this bug? I'm not sure that I've ever experienced it, which either means that I'm immune (:raised_hands:) or it's gone.
