### ISSUE TITLE
Sort channel messages chronologically

### ISSUE THREAD

**Issue by anandthakker** [ssbc/patchbay#61]
Caveat: I'm only about 10 minutes in to using ssb and patchbay.

Following the README here, I got the sbot server set up w/ plugins, and restarted.  Connected to a pub (`@pub_cel`) w/ invite from IRC, followed `@pub_cel`, and opened #scuttlebutt channel.

Plenty of messages appear in the tab, but they don't seem to be in any sort of order.  (I see, in order, 1 msg from 12 minutes ago, 5 from 7 months ago, 5 from 3 days ago, etc.)

Is this the wrong place for this issue?  Is it user error?  Apologies if so.

**Comment by dominictarr** [comment]
first of all - please feel welcome to post an issue that you think might be a "user error" that helps us understand how people use the software, and what things seem obvious to them. it's not a user error it's a usability error.

So, the main reason for this is that the ordering of messages is the order you received them locally. when you do the initial sync, they won't be ordered very well, but once you use it regularily, you'll tend to receive messages as they arrive, and then it will be better.

part of the difficulty here is that you don't necessarily receive messages in the same order that I do,
you can make messages while offline, then share them over wifi, so we may receive someone's messages in very different orders, as well as in realtime.

This makes it quite difficult to figure out what the correct order is. Maybe we could show old messages in sorted order, then append new messages on top...

Actually, what about show all old messages in order, and messages that have arrived since you last looked at the top? what do you think @clehner ?

**Comment by clehner** [comment]
> show all old messages in order, and messages that have arrived since you last looked at the top?

So to change fetching the old messages to use createFeedStream instead of createLogStream? I think that would be good

**Comment by clehner** [comment]
For new messages, it might help if they are buffered and sorted before being prepended to the view. I think this could be done by pulling new messages through a stream that buffers and sorts them using a priority queue.

**Comment by anandthakker** [comment]
> For new messages, it might help if they are buffered and sorted before being prepended to the view. I think this could be done by pulling new messages through a stream that buffers and sorts them using a priority queue.

^ Yeah, FWIW, I think something like this is what I was intuitively expecting, understanding that (especially at initial sync) the list of messages I see wouldn't necessarily be _populated_ in order -- since it seems like, even if the messages aren't indexed by timestamp in the underlying db, the subset being shown in any given view should be few enough to be buffered/sorted.

**Comment by clehner** [comment]
Progress:
https://www.npmjs.com/package/pull-buffer-sort
http://localhost:7718/%25zjzB39r9UoTbX8E%2FmD6y1bSjBouL9ukdkSCGbF40B08%3D.sha256

**Comment by evbogue** [comment]
This didn't get done, and is still an issue.
