### ISSUE TITLE
How to run patchbay on a mobile phone

### ISSUE THREAD

**Issue by oren** [ssbc/patchbay#65]
@evbogue mentioned it's possible to run patchbay lite on a mobile phone.

Here are the steps I took to make patchbay lite work on my **laptop**: 
```
cd patchbay
npm run lite
sbot server --allowPrivate
sbot invite.create --modern (in another terminal)
o file:///home/oren/p/patchbay/build/index.html#ws://localhost:8989~shs:Q1w9hSUpspxVVbGMuemxiOca7G0Q7FcFY5oflmkjJLk=:tGBXvR0NzVlmVhzbitJEexX5Sg3AAgYLb7NQSDM9NgQ=
```

Now, how do I run patchbay on my mobile phone?

Thanks!

**Comment by evbogue** [comment]
@oren Bay needs to collect to an sbot daemon via websockets. Doing this on your local is easier, because you don't need to enable https.

I wrote this article in September, but it might be a little out of date: https://evbogue.com/liteclientpub/

Basically you need 

+ an sbot pub on a vps
+ with https enabled (I've been using caddy)
+ serve the lite client from your server
+ generate a lite client invite
+ concat the invite with the location of the server
+ send your phone the invite and click it

(this all could be easier)

I have 100 of these remote invites set up here, if you want to try one https://evbogue.com/100invites

**Comment by oren** [comment]
got it. thanks.

another question, how do i use the lite again? here are the steps i follow:
```
cd patchbay
npm run lite
sbot server --allowPrivate
sbot invite.create --modern (in another terminal)
o
file:///home/oren/p/patchbay/build/index.html#ws://localhost:8989~shs:Q1w9hSUpspxVVbGMuemxiOca7G0Q7FcFY5oflmkjJLk=:tGBXvR0NzVlmVhzbitJEexX5Sg3AAgYLb7NQSDM9NgQ=
```
(the last command has different string of course)

the problem is i can't see anything in /private so i think i can't send
direct messages to members. am i doing something wrong?

**Comment by oren** [comment]
sorry 'o' is alias form opening my chrome.

**Comment by evbogue** [comment]
@oren Private messages are a little broken in the lite client (threads don't work), so they're disabled if you're using Patchbay master right now. I think if you move your desktop key into the lite client (since it's local), private messages will work.

```
cat .ssb/secret
```
copy the key and paste it into your lite client by opening the import/export '/key' page using the dropdown you can find by mousing over the blue status light.

I've made these things a little easier in the fork I'm working on: https://github.com/evbogue/minbay but some of the features haven't quite made it to master. I've also just enabled private messages, because I don't mind so much that threads are broken.

What needs to happen to get private messages working in the lite client, for real, is to move more data into the browser.

**Comment by oren** [comment]
got it. thanks!
